import { NextResponse } from "next/server";
import { getDbConnection, sql } from "@/lib/db";
import { hashPassword } from "@/lib/password";

export async function POST(req: Request) {
    try {
        const { username, password, full_name } = await req.json();

        if (!username || !password || !full_name) {
            return NextResponse.json({ success: false, error: "Missing fields" }, { status: 400 });
        }

        if (!username.endsWith('@ttigroup.com.vn')) {
            return NextResponse.json({ success: false, error: "Email must end with @ttigroup.com.vn" }, { status: 400 });
        }

        const pool = await getDbConnection();

        // Check if user exists
        const check = await pool.request()
            .input('username', sql.NVarChar, username)
            .query("SELECT username FROM users WHERE username = @username");

        if (check.recordset.length > 0) {
            return NextResponse.json({ success: false, error: "Tên đăng nhập đã tồn tại" }, { status: 400 });
        }

        const hashedPassword = await hashPassword(password);

        // Insert user
        // Note: Assuming 'role' defaults to 'user' in DB or we set it.
        // And 'id' is generated by DB (default) or we need to generate it?
        // Azure SQL UNIQUEIDENTIFIER DEFAULT NEWID() usually.
        await pool.request()
            .input('username', sql.NVarChar, username)
            .input('password', sql.NVarChar, hashedPassword)
            .input('full_name', sql.NVarChar, full_name)
            .input('role', sql.NVarChar, 'user')
            .query(`
        INSERT INTO users (username, password, full_name, role)
        VALUES (@username, @password, @full_name, @role)
      `);

        return NextResponse.json({ success: true, message: "User created" });

    } catch (error: any) {
        console.error("Signup API Error:", error);
        return NextResponse.json({ success: false, error: error.message || "Internal Server Error" }, { status: 500 });
    }
}
